version: '2'
services:
  funadf_app:
    container_name: funadf_app
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: ${COMMAND}

    ports:
      - '3001:3001'
    volumes:
      - /var/tmp
      - .:/app
    depends_on:
      - funadf_db
    extends:
      file: ./docker/mysql/password.yml
      service: password

  funadf_db:
    container_name: funadf_db
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3308:3307'
    volumes:
      - funadf_recette_db:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password

volumes:
  funadf_db: